javalent/initiative-tracker

.gitignore, src/utils/conditions.ts
Hi! I really love this plugin - thank you for creating it! I used it in my Sunday game and really missed being able to track who is concentrating on a spell (useful so that I as the DM can prompt them to make concentration checks if necessary) and who has already used their reaction. To this end, I've added "Concentrating" and "Reacted" to the conditions list, along with descriptions of each.
Let me know what you think!
=> Added Concentrating and Reacted to conditions

src/view.ts
Calling `updateCreature` *adds* `creature.max` to a creature's hp instead of *setting* the hp.
This fix manually sets HP to the maximum value.
(I have no ts knowledge so there might be a better solution ;))
=> Fix bug in resetEncounter

@types/index.d.ts, src/settings.ts, src/svelte/Table.svelte, src/utils/constants.ts, src/view.ts
Static changes:
- Active creature highlighting in table made more clear when using Obsidian's dark theme, former hightlighting exists as base case for any other themes
- When attempting to move backwards in the initative order during round 1, the active creature stops at the first creature in the list, instead of wrapping
- Behaviour for other rounds remain unchanged
The following features are added as toggleable settings:
- Clamping minimum HP to 0
- Automatically add the "Unconscious" status to creatures falling below 0 HP
Note:
It seems from the code that wrapping round 1 over and over when traversing backwards through the initiative order might've been an intentional feature. The changes that stop this behaviour were initially created before I made the dark theme visibility update, …
=> QOL updates for HP management, visibility update for obsidian dark theme

src/encounter/ui/Encounter.svelte
(includes changes of #42 )
When using the dice roller plugin, the XP of one or more creatures does not update when new values are rolled (value in parentheses). This PR adds reactivity by reassigning (cloning) the `creatureMap` object which is modified when a new value is rolled.
=> Fix xp diceroller

src/encounter/ui/Encounter.svelte
Fixes #26 
The XP in the tooltip within the note is incorrectly calculated (see [here](https://github.com/valentine195/obsidian-initiative-tracker/blob/master/src/encounter/ui/Encounter.svelte#L46-L54)). This PR fixes the following issues
1. The XP values are added without considering the number of creatures. 
2. The `totalXP` is calculated from an empty `Map`.
3. Currently the `creatures` instead of the `creatureMap` object is used. The latter is modified if dice rolling is enabled and thus should be used. 
Fixes:
1. use `creatureMap` instead of `creatures`
2. calculate `totalXP` after populating `creatureMap` and use `creatureMap` as source.
3. use `creatureMap` to compute difficulty and consider number of creatures. This is done by creating an array that has repeated entries for the …
=> Fix bug in display of XP in difficulty tooltip in note

@types/index.d.ts, README.md, src/settings.ts, src/svelte/App.svelte, src/svelte/Creature.svelte, src/utils/constants.ts, src/utils/creature.ts, src/view.ts
- Can now add temporary HP when applying damage/healing by prefixing with t
- prefixing with both t and - will remove temp HP (to a minimum of 0)
- Any creature with temp HP will have their current HP displayed in bold text
- Hover over a creature's current HP to see how much of it is temp HP
- Intentionally does not appear when temp HP is 0, but this can be changed if desired
- Moved previously added HP settings to its own menu under "Battle", along with "Addtive Temporary HP" and "Healing Overflow"
- Additive Temporary HP is added as a option for edge cases where one might not want temp HP to be overwritten
- Healing Overflow grant three different options for how to handle healing above a creature's max HP
- Ignore: HP above the max HP threshold is ignored
- Temp: HP above the max HP …
=> Add temporary HP feature and healing overflow settings

README.md, src/svelte/App.svelte, src/svelte/Creature.svelte, src/svelte/CreatureControls.svelte, src/svelte/Table.svelte, src/utils/constants.ts
- Multiple creatures can now be selected at once for damage/healing application in the table view
- Select multiple creatures by clicking while holding CTRL
- Apply half damage/healing by clicking while holding ALT
- Apply "successful saving throw" (half damage/healing + no condition applied) by clicking while holding SHIFT
- Half damage/healing is always rounded down, unless the number provided contains a ".", e.g.:
- 5/2 = 2
- 5./2 = 2.5
- 5.3/2 = 2.65
- Creatures selected for damage/healing application are put into a separate table at the bottom of the view
- Useful for differentiating between creatures succeeding/failing saving throws
- Tablet users can easily set the "saved" and "resist" properties using the UI
- The extra modifier field can be used for effects like a Grave Cleric's …
=> Add damage/healing to multiple creatures

@types/index.d.ts, README.md, src/settings.ts, src/svelte/App.svelte, src/utils/constants.ts
closes #59
- beginnerTips added as an option
- hides instructions in UI when disabled
- apply and Cancel buttons aligned with damage/status fields
Check-in to: master
=> feat: Add option to remove beginner tips

src/svelte/Creature.svelte, src/svelte/Table.svelte
closes #57
- holding ctrl/meta now doesn't always add creature to damage/staus application
- clicking specifically on the name of a creature will open its statblock
- clicking a creature's HP or AC field will always add a creature to damage/status application
Check-in to: master
=> fix: remove creature selection shortcut overload

@types/index.d.ts, src/main.css, src/main.ts, src/settings.ts, src/svelte/Creature.svelte, src/utils/constants.ts, src/utils/creature.ts, src/view.ts
- Toggle setting: Render statblock link content in the creature view
- `statblock-link` attribute is parsed (block-ref, section, or full document), and content is included in the creature view
- Added a timeout to make the hover over the monster/creature name in the initiative order less sensitive.
=> Statblock link

src/main.ts, src/tracker/view.ts
Somehow it seems like some of the code in `view.ts` from [this pr](https://github.com/valentine195/initiative-tracker/pull/92) by @ebullient got lost at some point. The setting to use the statblock links is still there, but does nothing. This PR just brings back that functionality.
=> Bring back statblock-link functionality

src/encounter/index.ts
Fixes the following documented encounter syntax that is currently not working correctly:
````
```encounter
-
- [Hobgoblin, Jim]
- 12
- 13
- 2
- 25
```
````
The same syntax works with the creature count specified but fails in this case since it previously interpreted the array as an object and only used the creature & display name but discarded the stat overrides.
=> fix: fixes stats parsing for single creatures with a display name

src/main.ts, src/settings/settings.ts, src/tracker/ui/creatures/Creature.svelte, src/tracker/view.ts, src/utils/creature.ts
Defer construction of statblock link (resolving anchor links) until render time, so it catches all paths.
=> 🐛 defer construction of statblock link

src/tracker/stores/tracker.ts
- Iterate forwards and backwards around disabled creatures.
- Include the non-zero creature number when adding their turn to the log
=> 🐛 iterate over disabled creatures; log with name & number

README.md, src/encounter/ui/EncounterLine.svelte, src/main.ts
Enable stat overrides and display names for inline encounters:
```
`encounter: [[Hobgoblin, Jim], 12, 13, 2, 25], 2: [[Hobgoblin, Jeff], 12, 13]` 
```
This is made possible by simply parsing the inline creature list as a YAML array instead of manually splitting the list and parsing the creatures individually.
This makes it possible to use `,` in the inline encounter syntax and thus the YAML array syntax already supported by the regular encounter block.
The display code is in turn updated to show the display name for inline encounters, same as for regular encounters.
I've updated the README to document this syntax and added single-line-YAML-array examples to the encounter block examples as well for consistency.
I also added some examples showing how to reference a creature with a `,` in …
=> feat: enable inline encounter creature stats & display name changes

src/tracker/stores/tracker.ts
The idea is to set the flag for the unconscious status in the message if we know that the update will bring the creature below 0 HPs...
=> fix: properly log automatic unconscious status (close #132)

index.ts, src/logger/logger.ts, src/settings/settings.ts, src/tracker/ui/creatures/Status.svelte
Without this change:
- Any change done to a status' amount would be lost (and the value reset to the starting amount) as soon as the turn advances;
- When multiple statuses are assigned, only 2 were logged, instead of the full list.
=> fix: handling of status amounts and logging of receiving multiple statuses

@types/index.d.ts, README.md, package-lock.json, package.json, src/tracker/stores/tracker.ts, src/tracker/ui/Updating.svelte, src/tracker/ui/create/Creator.svelte, src/tracker/ui/creatures/Table.svelte, src/utils/creature.ts
Creatures' max HP can take damage and receive healing through the "m" prefix.
creature.current_max is introduced as a variable to ensure resetting the encounter also resets max HP.
The rules for reducing max HP follow the standard rules in 5e:
Damage to max HP is applied after normal damage.
Creature HP can't be higher than max HP (rule disabled if overflow healing is enabled).
Max HP has a lower clamp at 0.
Additionally, temp HP can now be subtracted to remove only the temp HP.
Useful for scenarios such as removing all temp HP from multiple creatures affected by the Heroism spell.
Check-in to: master
=> feat: Add functionality for max HP damage

index.ts, src/main.ts, src/settings/settings.ts, src/tracker/ui/Controls.svelte, src/tracker/ui/creatures/CreatureControls.svelte, src/tracker/view.ts, src/utils/constants.ts, src/utils/icons.ts
BEGIN_COMMIT_OVERRIDE
feat!: This removed the feature of Leaflet integration. However, this feature has been broken.
BREAKING CHANGE: As this is a removal of an existing feature, this is technically a breaking change.
END_COMMIT_OVERRIDE
=> Feat!(Battlemap): Integration with Obsidian Leaflet removed

src/settings/settings.ts
Avoids failures caused by the user defining frontmatter as a string instead of a number, such as trying to concatenate numbers as strings instead of adding
Fixes #291
=> Use parseInt when reading PC definitions

src/tracker/ui/Updating.svelte
Functionality added to add condition to the condition view when clicking enter or selecting the condition from the dropdown,. Check for enter also added to conditionDiv to ensure the same behaviour holds true for custom/improvised conditions.
Proposed changes are made to streamline workflow by ensuring users won't have to leave the comfort of their keyboard between typing and adding a condition.
=> fix: add condition on select

src/logger/logger.ts, src/logger/logger.types.ts, src/tracker/stores/tracker.ts, src/tracker/ui/creatures/Creature.svelte, src/utils/creature.ts
Add functions addCondition and removeCondition to creature.ts to allow for better handling of conditions. Add remove_status field to CreatureUpdate, which is used to call creature.removeCondition. Add remove_status to logger.types.ts and move logging of condition removal to the logger
Change behaviour upon reapplying a condition to not change the state of the tracker if the conditions are considered equal.
Note that comparisons on IDs is specifically not done in order to avoid problems with improvised conditions.
Fixes #297
=> fix: reapplying conditions no longer removes them

.prettierrc, src/tracker/stores/tracker.ts
Did an oopsie and didn't notice a 1300 line file got linted with different settings.
Adding an appropriate .prettierrc file to ensure the same doesn't happen again, and lint the file with the correct settings.
Undo a bad change
=> fix: add linter settings & revert accidental lint

src/settings/settings.ts, src/settings/settings.types.ts, src/tracker/stores/tracker.ts, src/tracker/ui/creatures/Table.svelte, src/utils/constants.ts, src/utils/creature.ts
Add an option to define how initiative ties are resolved.
Default is players first, similar to existing behaviour (not explicitly defined, but players seem to be added to encounters before other creatures). Other options are NPCs first or random.
Fixes #294 by adding an option to make NPCs win initiative ties
=> Add initiative ties resolution setting

src/utils/rpg-system/dnd5e-cr2-simple.ts, src/utils/rpg-system/dnd5e-flee-mortals.ts
This fixes issues with the encounter builder and the CR2.0 and Flee Mortals XP systems. 
- Fixed a bug in Flee Mortals that would result in undefined values when no party was loaded into the encounter builder.
- Fixed a bug in CR2.0 where an invalid function would be called on an empty array when no party was loaded into the encounter builder.
- Fixed the spelling of "Bloody" in the CR2.0 system.
Fixes #309 
BEGIN_COMMIT_OVERRIDE
fix: Fixes misspelling of Bloody in CR2.0
fix: Fixes some instances of the encounter builder not loading for some XP systems
END_COMMIT_OVERRIDE
=> Fixes the Encounter Builder not loading when using CR2.0 or Flee Mortals XP systems
